# Generated by Django 6.0.4 on 2026-04-30 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
    ]
