# Generated by Django 6.0.4 on 2026-04-28 22:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certificate_number', models.CharField(max_length=100, unique=True)),
                ('verification_hash', models.CharField(max_length=256, unique=True)),
                ('blockchain_tx_hash', models.CharField(blank=True, max_length=256)),
                ('blockchain_network', models.CharField(blank=True, max_length=50)),
                ('is_blockchain_verified', models.BooleanField(default=False)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificates/pdfs/')),
                ('cloudinary_url', models.URLField(blank=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('metadata', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='certificates/templates/')),
                ('html_template', models.TextField(blank=True)),
                ('css_styles', models.TextField(blank=True)),
                ('primary_color', models.CharField(default='#1e293b', max_length=7)),
                ('secondary_color', models.CharField(default='#6366f1', max_length=7)),
                ('font_family', models.CharField(default='Georgia', max_length=100)),
                ('logo_position', models.CharField(default='top-center', max_length=20)),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='certificates/signatures/')),
                ('signatory_name', models.CharField(blank=True, max_length=200)),
                ('signatory_title', models.CharField(blank=True, max_length=200)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
