# Generated by Django 6.0.4 on 2026-04-28 22:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('text_translations', models.JSONField(default=dict)),
                ('is_correct', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('description_translations', models.JSONField(default=dict)),
                ('instructions', models.TextField(blank=True)),
                ('max_score', models.IntegerField(default=100)),
                ('passing_score', models.IntegerField(default=60)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('allow_late_submission', models.BooleanField(default=False)),
                ('late_penalty_percent', models.IntegerField(default=10)),
                ('allowed_file_types', models.JSONField(default=list)),
                ('max_file_size_mb', models.IntegerField(default=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed')], default='published', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('grading', 'Being Graded'), ('graded', 'Graded'), ('returned', 'Returned for Revision')], default='submitted', max_length=20)),
                ('content', models.TextField(blank=True)),
                ('files', models.JSONField(default=list)),
                ('score', models.FloatField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('is_late', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('multi_select', 'Multi Select'), ('true_false', 'True / False'), ('short_answer', 'Short Answer'), ('essay', 'Essay'), ('fill_blank', 'Fill in the Blank'), ('matching', 'Matching'), ('ordering', 'Ordering')], default='mcq', max_length=20)),
                ('text', models.TextField()),
                ('text_translations', models.JSONField(default=dict)),
                ('explanation', models.TextField(blank=True)),
                ('explanation_translations', models.JSONField(default=dict)),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/')),
                ('points', models.IntegerField(default=1)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_ai_generated', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('title_translations', models.JSONField(default=dict)),
                ('description', models.TextField(blank=True)),
                ('quiz_type', models.CharField(choices=[('practice', 'Practice Quiz'), ('graded', 'Graded Quiz'), ('final', 'Final Exam'), ('survey', 'Survey')], default='graded', max_length=20)),
                ('time_limit_minutes', models.IntegerField(blank=True, null=True)),
                ('passing_score', models.IntegerField(default=70)),
                ('max_attempts', models.IntegerField(default=3)),
                ('shuffle_questions', models.BooleanField(default=True)),
                ('shuffle_answers', models.BooleanField(default=True)),
                ('show_answers_after', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('graded', 'Graded'), ('timed_out', 'Timed Out')], default='in_progress', max_length=20)),
                ('score', models.FloatField(blank=True, null=True)),
                ('score_percentage', models.FloatField(blank=True, null=True)),
                ('passed', models.BooleanField(blank=True, null=True)),
                ('time_taken_seconds', models.IntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('answers_data', models.JSONField(default=dict)),
                ('attempt_number', models.IntegerField(default=1)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('browser_info', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
