# Generated by Django 6.0.4 on 2026-04-30 21:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('tenant_type', models.CharField(choices=[('school', 'School / University'), ('corporate', 'Corporate Training'), ('bootcamp', 'Bootcamp / Academy'), ('ngo', 'NGO / Non-profit'), ('individual', 'Individual Creator')], default='school', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('trial', 'Trial'), ('pending', 'Pending Setup')], default='trial', max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tenants/logos/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='tenants/favicons/')),
                ('primary_color', models.CharField(default='#6366f1', max_length=7)),
                ('secondary_color', models.CharField(default='#8b5cf6', max_length=7)),
                ('accent_color', models.CharField(default='#06b6d4', max_length=7)),
                ('text_color', models.CharField(default='#1e293b', max_length=7)),
                ('background_color', models.CharField(default='#ffffff', max_length=7)),
                ('font_family', models.CharField(default='DM Sans', max_length=100)),
                ('custom_css', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('default_language', models.CharField(default='en', max_length=5)),
                ('supported_languages', models.JSONField(default=list)),
                ('custom_domain', models.CharField(blank=True, max_length=253)),
                ('max_students', models.IntegerField(default=50)),
                ('max_instructors', models.IntegerField(default=5)),
                ('max_storage_gb', models.FloatField(default=5.0)),
                ('used_storage_gb', models.FloatField(default=0.0)),
                ('owner_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('settings', models.JSONField(default=dict)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant', to='subscriptions.subscription')),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
            },
        ),
    ]
