# Generated by Django 6.0.4 on 2026-04-28 22:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('tier', models.CharField(choices=[('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise'), ('custom', 'Custom')], max_length=20)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10)),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_description', models.CharField(blank=True, max_length=100)),
                ('stripe_price_id', models.CharField(blank=True, max_length=100)),
                ('max_students', models.IntegerField(default=50)),
                ('max_instructors', models.IntegerField(default=5)),
                ('max_courses', models.IntegerField(default=10)),
                ('max_storage_gb', models.FloatField(default=5.0)),
                ('max_admins', models.IntegerField(default=1)),
                ('bandwidth_gb', models.FloatField(default=50.0)),
                ('has_live_classes', models.BooleanField(default=False)),
                ('has_ai_features', models.BooleanField(default=False)),
                ('has_certificates', models.BooleanField(default=False)),
                ('has_blockchain_certs', models.BooleanField(default=False)),
                ('has_custom_branding', models.BooleanField(default=False)),
                ('has_custom_domain', models.BooleanField(default=False)),
                ('has_api_access', models.BooleanField(default=False)),
                ('has_advanced_analytics', models.BooleanField(default=False)),
                ('has_gamification', models.BooleanField(default=False)),
                ('has_marketplace', models.BooleanField(default=False)),
                ('has_mobile_app', models.BooleanField(default=False)),
                ('has_sso', models.BooleanField(default=False)),
                ('has_white_label', models.BooleanField(default=False)),
                ('has_priority_support', models.BooleanField(default=False)),
                ('has_scorm', models.BooleanField(default=False)),
                ('has_multi_language', models.BooleanField(default=True)),
                ('has_bulk_enrollment', models.BooleanField(default=False)),
                ('has_zoom_integration', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('features_list', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('is_popular', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
                'ordering': ['sort_order', 'price_usd'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('past_due', 'Past Due'), ('trialing', 'Trialing'), ('paused', 'Paused'), ('expired', 'Expired')], default='trialing', max_length=20)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('trial_start', models.DateTimeField(blank=True, null=True)),
                ('trial_end', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.plan')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_invoice_id', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(max_length=20)),
                ('invoice_pdf', models.URLField(blank=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='subscriptions.subscription')),
            ],
        ),
    ]
