# Generated by Django 6.0.4 on 2026-04-28 22:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_views', models.IntegerField(default=0)),
                ('total_enrollments', models.IntegerField(default=0)),
                ('total_completions', models.IntegerField(default=0)),
                ('completion_rate', models.FloatField(default=0)),
                ('average_progress', models.FloatField(default=0)),
                ('average_rating', models.FloatField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('average_watch_time_minutes', models.FloatField(default=0)),
                ('drop_off_data', models.JSONField(default=dict)),
                ('daily_stats', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TenantAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total_users', models.IntegerField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('new_enrollments', models.IntegerField(default=0)),
                ('completions', models.IntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_watch_minutes', models.IntegerField(default=0)),
                ('quiz_attempts', models.IntegerField(default=0)),
                ('certificates_issued', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('login', 'Login'), ('lesson_view', 'Lesson View'), ('lesson_complete', 'Lesson Complete'), ('quiz_attempt', 'Quiz Attempt'), ('assignment_submit', 'Assignment Submit'), ('course_enroll', 'Course Enroll'), ('course_complete', 'Course Complete'), ('certificate_earn', 'Certificate Earned'), ('forum_post', 'Forum Post'), ('live_class', 'Live Class')], max_length=30)),
                ('metadata', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_info', models.JSONField(default=dict)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
